# Generated by Django 5.2.4 on 2025-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
