# Generated by Django 5.2.4 on 2025-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_backend', '0002_datasource_processing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='is_active',
        ),
        migrations.AddField(
            model_name='datasource',
            name='processing_config',
            field=models.JSONField(blank=True, help_text='Configuration for document processing', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='processing_status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='unprocessed', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('txt', 'Text File')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
