# Generated by Django 5.2.4 on 2025-07-28 13:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_backend', '0003_alter_datasource_options_remove_datasource_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='location',
        ),
        migrations.AddField(
            model_name='datasource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads/', location='uploads/'), upload_to='sources/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this data source is active for use'),
        ),
    ]
